project:
  type: book

book:
  title: "ORD Proposal: opnts"
  subtitle: ": An Open Framework for Scientific Grade Time Series Datasets"
  author: "Dr. Matthias Bannert and Minna Heim"
  date: "1/18/2024"
  chapters:
    - index.qmd
    - wp0.qmd
    - wp1.qmd
    - wp2.qmd
    - wp3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  #pdf:
  #  documentclass: scrreprt



