# Impact 

<!-- **Instructions**
Please address these specific points:

- How sustainable is the proposed project inside the ETH Domain?

- To what extent will the planned project substantially advance the ORD field, or solve a critical outstanding problem in the targeted field(s)?

- To what extent does the proposal support a collaborative approach,
  involving significant synergies, complementarities, or/and scientific
  added-value to achieve its objectives? -->


It is particularly important to us to not only solve a critical problem of our community, but also to do so in sustainable fashion. We are convinced that aligning opents with the FAIR principles is instrumental to establish our approach in our own community and to reach other research communities from there. 

## Sustainability in the ETH Domain

Regular and timely data sourcing is manadatory for KOF's academic and national tasks. 
Hence we are fully convinced that pushing an ORD approach at KOF, will help advances ORD practices in empirical economics and official statistics in the long term. 
The usage of the opnts framework in teaching and the economic community helps to leverage digital transformation efforts in official statistics as future researchers and public servants alike become familiar with Swiss official statistics data and ORD principles. 
In addition, our inclusive approach helps to keep the community involved while the idea of modular software packages with their maintainers allows to pass on responsibilities in case of changes in personnel.
The Comprehensive R Archive Network (CRAN) and the R Project for Statistical Computing has a long tradition at ETH.
The ETH domain and its staff contributed substantially to the language and its extension packages including to CRAN itself^[see also https://stat.ethz.ch/CRAN/]. 

## Solving a Critical Problem

Although there has been a certain sense of urgency for digital transformation in the public sector since the pandemic at the latest, change management schedules do not always align with the timeline of individual academic careers or ongoing daily business. 
While we greatly appreciate advances in the above efforts, we provide an immediate solution to data sourcing to those that need to ingest public data today. 
In addition, we help identify redundant efforts across institutions and broker usage of a common sources, using public money more efficiently. 
Finally, we help bridge the gap and strengthen the link between public administration and academic research.



## Collaboroative Approach

The proposed opnts project is highly collaborative in multiple ways. 
The technical approach is inclusive and modular: Through open-sourcing and focusing the core package we hold ourselves accountable through the community and at the same encourage contribution to the technical core. 
Our data provider specific modules we foster collaboration at the dataset level.
Through our own dataset modules, we provide examples which collaborators from other fields can use - along with the documentation - as blueprints to build their own extension packages to process data from their respective fields. 
Last but not least we involve data providers from the very initial phase of the project.
Our goal is to use our traditional ties with federal and regional public administration to establish a channel for hands-on two way feedback betweend data providers and the research community.
In the process we plan to take part in existing academic and non-academic community events and also explore ways and formats, particularly in a way of teaching involves students to our collaborative approach. 


## FAIR Principles 

Our approach is designed to foster *findable* output. 
We combine our own experience with the expertise of our partners to find the right outlets for our time series data and software to reach multiple communities.
A high degree of automation allows us to maintain our output on several outlets from GitHub to CRAN, but also subject our work to scientific reviews such 


 our automated approach allows us to publish to different platforms, data and software side: (on github, rOpenSci, and Dryad platforms, CRAN)

- *accessible* we open source it, find right licence, ETH rechtdienste, publish with low hurdles, but also on those that are more convenient and less accessible, i.e. CRAN because low barriers to entry when publishing software on Github (and other OS platforms) and data on Zenodo (and other OS platforms), integrated into teaching

- *interoperable* because of the ability to add supplementary packages, where researchers can apply the opnts software to their field 

- *interoperable* because can be used in different languages, no matter which language, operating system - even across culture the "look at data people can understand" -> excel, google spreadsheets 

- *reusable* because we publish data and framework and even the infrastructure as code. community service, reachable through matrix channel, maintainer concept (find maintainers for specific datasets, specific fields, through maintainer of CRAN)


