# Introduction


|  |  |
|:-----|:----|
|   Full title  |  opnts - An Open Framework to Create Scientific Grade Time Series Datasets from Public Data
  |
|  Keywords |  Open Data, Official Statistics, Time Series Analysis, Data Literacy, Automation, Machine Readability, Community
 |


## Problem Statement

 Opnts bridges the gap between official statistics and academic research. Even though public availability of official statistics is decent (in Switzerland), data publications of regional and federal public data providers lack machine readability. Therefore these data publications are inconvenient to use for academic researchers.

 In the field of economics, for example, intertemporal comparisons play an important role. This implies regular and timely ingestions of data. Traditional data publications of (time series data) are often unsuitable as an interface between the data provider and the scientific consumer. 

 <!-- insert bfs excel (example of a data publication that is hard to ingest by a machine)-->
 
 Though application programming interfaces (APIs) from the official providers have lead to great improvements of machine reability of public data, the machine readability of public data is not homogenous across datasets.  Because modern economic (forecasting) models make use of hundreds of variables stemming from a large range of datasets, this heterogeneity is particularly troublesome for scientific use and the monitoring of the Swiss economy. Opnts mitigates this dynamic problem by providing an open technical framework, to ease the data sourcing and quality control burden, and by establishing a steady exchange (collaboration) between regional and federal data providors and its academic community.


- waste of resources, no solution while waiting for digital transformation, highly dynamic -> can't wait.
- data publication vs. time series, scientific use. 
- data is often publicly available but hard to digest for machines
- undeniably OGD has had great impact, data quality remains heterogeneous, particularly w.r.t. machine readability.
- methodological and technical advances (computing power) open up new possibilities but require high degrees of automation in data ingestion when models use large amounts of time series
- higher frequency, e.g., immediate evaluation of measures during COVID-19 regulations. 
- evaluation of forecasts (benchmark) ask for automation

<!-- in 2 ways: 

1. improving & spreading ORD practices (active discussions with FSO, teaching, FAIR principle inclusion)
2. code as communication (framework as a blueprint to communicate what we want to do, as an interim solution).

-> erhöhe abstraktionsniveau, wir haben communication and technisches framework, bilden wissen, was bfs uns gibt, und 2. community building.

:::{.callout-important}

bridging the gap between academia and official statistics. 
way to do it: streamline publication, inclusion across all working packages. share a blueprint process on how to work with public data. 
have different entrypoints for different needs: data, source code, meta data etc. 
code as a communication channel,

::: -->


## Background and Motivation

Though we aim to extend the approach suggested in this proposal to other fields in the future, this *Explore* proposal focuses on our 'homecourt' disciplines of public statistics and empirical economics.
We are confident that our strong network in both of these fields will leverage our initial push enough to give the impact of the *opents* project a great chance to spill over to other communities. 
The following sections introduce our background and explains how the proposed project helps the economics, forecasting and open data communities. 

### Time Series Analysis, Forecasting and Data Science in Economics

Time Series analysis continues to play an important role in many strands of modern empirical economics: 
Economic forecasting and its evaluation, studies of shock absorption and many other econometric modelling exercises ask for data that allow intertemporal comparison. 
Modern models often use hundreds or even thousands of time series. 

Even though machine readability of publicly available data has improved in Switzerland thanks to great efforts led by the Swiss Federal Statistical Office (SFSO), researchers face a publication mindset that is focused on the wider public and hence on the most recent wave of data. 
As a consequence, variable names or features may change over time and minor errors may simply get corrected adhoc or with the next publication – even in datasets that are already available through an application programming interface. 
In combination with different degrees of machine readability across different providers of public data, the issues mentioned above can lead two very heterogeneous situation when it comes to automated data ingestion – particularly for those researchers who need a large amount of data from a variety of providers. 

Our motivation is to help the time series community immediately while larger organizations face different restrictions and need to move slower. 
We intend to do so by not only open sourcing a framework to create scientific use grade time series from official statistics, but also publishing our framework in the most inclusive way possible: 
i) we focus on thorough documentation that involves the community, ii) we provide comprehensive application examples making many thousand proven time series available, iii) through an infrastructure-as-code approach, we give precise information on how to set up an environment that is capable of running our framework. 





### Sustainability through Cooperation: Official Statistics and Public Data

- at same time oru background in regular publication and identification with the official statistics community ensures sustainability of the opnts effort.



Even though machine readability of publicly available 
- research use publicly available data are published with a publication mindset
- APIs not free of the mindset
- Introduction of APIs is slow 
- our motivation: help ts community immediately as larger oragnizations move slower, publication of time series data that is homogeneous across providers helps research community immediately




- at the same active exchange with FSO etc. channels research communities needs into official statistics efforts





Hence machine readability and automation is key to process data and monitor revisions in such an amount of information.


In addition to the strong empirical focus of its academic research, the  KOF Swiss Economic Institute at ETH Zurich has a national mandate to monitor the Swiss economy.
In the process, KOF produces forecasts and indicators many of which rely on publicly available data provided by federal and regional administration. KOF is also involved (together with the ifo Institute in Munich) in the Joint Economic Forecast in Germany, which serves the German government as a benchmark for future economic development.

```{r,echo=FALSE,message=FALSE,warnings=FALSE}
#| fig-cap: "The KOF Economic Barometer is a forward looking indicator (FLI) for the Swiss economy. It is well received in Switzerland and used as the official FLI for Switzerland by the International Monetary Fund (IMF)."

library(kofdata)
library(tstools)
tsl <- get_time_series("ch.kof.barometer")
tsplot(tsl)


```

Time series data are an important common denominator for activities such as intertemporal comparisons, forecasting, benchmarking of forecasts, study of shock absorption and many other economic modelling excercises. 


In the opnts project, we intend to help the time series community by sharing our data ingestion framework as well as machine readable scientific use grade time series data. 
The latter will immediately help institutions such as the Swiss National Bank, the Secretariat of Economic affairs, regional offices as well as academic researchers who use these time series data. 
Sharing machine readable data mitigates data ingestion problems and lowers the need for redundant processing across institutions. 
In the long run, improvement in inclusivity will -- framework.



<!-- changes: mehr kompakt, mehr academic research (was sind die felder in ökonomischen fachzeitschriften, wo man zeitreihen braucht. gib noch r ts beispiel dazu, wie's automatisiert ausschaut) -->

<!-- bei shock absorption und education wusste nicht wie ich das in den text integriere? the monitoring of shock absorption through fiscal, monetary policy? education by chair gersbach und sturm? -->



- important source
- requirements of scientific use different from main focus: data publication. 





### Public Data / Open by default @ RSEED

Making economic data on Switzerland more visible and accessible is one of KOF's concerns. Given its role in academia and its resources which stem from the state (?), KOF is commited to making its data as open as possible, and as restricted as necessary. For this reason, the KOF, together with the Swiss Federal Statistical Office (FSO), has identified key economic data that are processed as Open Government Data (OGD) and made available on the opendata.swiss platform. For now, KOF has published its Economic Sentiment Indicator, Global and Swiss Barometers, and Employment Indicator. 

<!-- our background in public data, we already have open data, kof data, kof datenservice api, ts explorer -> we already do a lot -->



